;; Gramps key file
;; Automatically created at 2026/10/07 12:37:49

[interface]
list-pane-height=340
preview-pane-width=641

[spacing]
name-column-width=374
;;status-column-width=108
type-column-width=122

