;; Gramps key file
;; Automatically created at 2026/05/20 00:01:10

[localterm]
;;bg_sel_col='#ffffff'
;;config_id='LocalTerm'
config_schema='0.3.0'
fg_sel_col='#613583'
lang1_file='gramps-project-glossary-en_rev1.csv'
lang2_file='gramps-project-glossary-en.csv'
;;search_lang=1
;;show_anchor=0
;;track_changes=1
;;url_bas='https://gramps-project.org/wiki/index.php/'

